name: netcdf_2
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - attrs=19.3.0
  - backcall=0.1.0
  - bleach=3.1.4
  - bzip2=1.0.8
  - ca-certificates=2020.4.5.1
  - certifi=2020.4.5.1
  - cftime=1.1.1.2
  - curl=7.69.1
  - decorator=4.4.2
  - defusedxml=0.6.0
  - entrypoints=0.3
  - hdf4=4.2.13
  - hdf5=1.10.6
  - importlib-metadata=1.6.0
  - importlib_metadata=1.6.0
  - ipykernel=5.2.1
  - ipython=7.13.0
  - ipython_genutils=0.2.0
  - jedi=0.17.0
  - jinja2=2.11.2
  - jpeg=9c
  - jsonschema=3.2.0
  - jupyter_client=6.1.3
  - jupyter_core=4.6.3
  - krb5=1.17.1
  - ld_impl_linux-64=2.34
  - libblas=3.8.0
  - libcblas=3.8.0
  - libcurl=7.69.1
  - libedit=3.1.20170329
  - libffi=3.2.1
  - libgcc-ng=9.2.0
  - libgfortran-ng=7.3.0
  - liblapack=3.8.0
  - libnetcdf=4.7.4
  - libopenblas=0.3.9
  - libsodium=1.0.17
  - libssh2=1.8.2
  - libstdcxx-ng=9.2.0
  - llvm-openmp=10.0.0
  - markupsafe=1.1.1
  - mistune=0.8.4
  - nbconvert=5.6.1
  - nbformat=5.0.6
  - ncurses=6.1
  - netcdf4=1.5.3
  - notebook=6.0.3
  - numpy=1.18.1
  - openssl=1.1.1g
  - pandas=1.0.3
  - pandoc=2.9.2.1
  - pandocfilters=1.4.2
  - parso=0.7.0
  - pexpect=4.8.0
  - pickleshare=0.7.5
  - pip=20.1
  - prometheus_client=0.7.1
  - prompt-toolkit=3.0.5
  - ptyprocess=0.6.0
  - pygments=2.6.1
  - pyrsistent=0.16.0
  - python=3.6.10
  - python-dateutil=2.8.1
  - python_abi=3.6
  - pytz=2020.1
  - pyzmq=19.0.0
  - readline=8.0
  - send2trash=1.5.0
  - setuptools=46.1.3
  - six=1.14.0
  - sqlite=3.30.1
  - terminado=0.8.3
  - testpath=0.4.4
  - tk=8.6.10
  - tornado=6.0.4
  - traitlets=4.3.3
  - wcwidth=0.1.9
  - webencodings=0.5.1
  - wheel=0.34.2
  - xz=5.2.5
  - zeromq=4.3.2
  - zipp=3.1.0
  - zlib=1.2.11

